In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv(r'C:\Users\LENOVO\Downloads\Datasets\creditcard.csv')
df = dataset.copy()
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [5]:
X = df.drop(['Class'], axis = 1)
y = df.loc[:, 'Class']

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[['Amount']] = sc.fit_transform(X[['Amount']])
X

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V20       V21  \
0       0.462388  0.239599  0.098698  0.363787  ...  0.251412 -0.018307   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.524980  0.247998   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.208038 -0.108300   
4       0.095921  0.592941 -0.270533  0.817739  ...  0.408542 -0.009431   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  1.475829  0.213454   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.059616  0.214205   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.001396  0.232045   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.127434  0.265245   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.382948  0.261057   

             V22       V23       V24       V25       V26       V27       V28  \
0       0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1      -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2       0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3       0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4       0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   
...          ...       ...       ...       ...       ...       ...       ...   
284802  0.111864  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731   
284803  0.924384  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   
284804  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   
284805  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   
284806  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649   

          Amount  
0       0.244964  
1      -0.342475  
2       1.160686  
3       0.140534  
4      -0.073403  
...          ...  
284802 -0.350151  
284803 -0.254117  
284804 -0.081839  
284805 -0.313249  
284806  0.514355  

[284807 rows x 30 columns]

In [9]:
X1 = X.drop(['Time'], axis = 1)
X1.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28    Amount  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  0.244964  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724 -0.342475  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  1.160686  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  0.140534  
4  0.141267 -0.206010  0.502292  0.219422  0.215153 -0.073403  

[5 rows x 29 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1,y, test_size = .2, random_state = 42)

In [12]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [13]:
y_pred = rfc.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score

In [15]:
confusion_matrix(y_test, y_pred)

array([[56863,     1],
       [   21,    77]], dtype=int64)

In [16]:
accuracy_score(y_test, y_pred)

0.9996137776061234

In [17]:
from sklearn.metrics import recall_score

In [18]:
recall_score(y_test, y_pred)

0.7857142857142857

## SMOTE Algo

In [20]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
X_res, y_res = sm.fit_resample(X_train, y_train)

In [30]:
# X_train.head(25)

In [25]:
y_res.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [22]:
X_res.shape

(454902, 29)

In [23]:
X_train.shape

(227845, 29)

In [29]:
from sklearn.ensemble import RandomForestClassifier
rfc1 = RandomForestClassifier(random_state = 0)
rfc1.fit(X_res, y_res)

RandomForestClassifier(random_state=0)

In [31]:
y_pred1 = rfc1.predict(X_test)

In [36]:
confusion_matrix(y_test, y_pred1)

array([[56856,     8],
       [   16,    82]], dtype=int64)

In [33]:
accuracy_score(y_test, y_pred1)

0.9995786664794073

In [34]:
recall_score(y_test, y_pred1)

0.8367346938775511

## Undersampling

In [37]:
from imblearn.under_sampling import NearMiss
nr = NearMiss()
X_miss, y_miss = nr.fit_resample(X_train, y_train)

In [38]:
X_miss.shape

(788, 29)

In [39]:
from sklearn.ensemble import RandomForestClassifier
rfc2 = RandomForestClassifier(random_state = 0)
rfc2.fit(X_miss, y_miss)

RandomForestClassifier(random_state=0)

In [40]:
y_pred2 = rfc2.predict(X_test)

In [41]:
confusion_matrix(y_test, y_pred2)

array([[10388, 46476],
       [    2,    96]], dtype=int64)

In [42]:
accuracy_score(y_test, y_pred2)

0.18405252624556723

In [43]:
recall_score(y_test, y_pred2)

0.9795918367346939