In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r'C:\Users\LENOVO\Downloads\Datasets\Social_Network_Ads - Classification.csv')
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
X = dataset.iloc[:, [0,1]]
y = dataset.iloc[:, -1]

In [4]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X = sc.fit_transform(X)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .2, random_state = 42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knc = KNeighborsClassifier()
knc.fit(X_train, y_train)

KNeighborsClassifier()

In [7]:
y_pred = knc.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred)

array([[48,  4],
       [ 2, 26]], dtype=int64)

In [9]:
accuracy_score(y_test, y_pred)

0.925

# SVM

In [10]:
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf')
svc.fit(X_train, y_train)

SVC()

In [11]:
svc_y_pred = svc.predict(X_test)

In [12]:
confusion_matrix(y_test, svc_y_pred)

array([[47,  5],
       [ 1, 27]], dtype=int64)

In [13]:
accuracy_score(y_test, svc_y_pred)

0.925

# GaussianNB

In [14]:
from sklearn.naive_bayes import GaussianNB
gnb= GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [15]:
gnb_y_pred = gnb.predict(X_test)

In [16]:
confusion_matrix(y_test, gnb_y_pred)

array([[50,  2],
       [ 3, 25]], dtype=int64)

In [17]:
accuracy_score(y_test, gnb_y_pred)

0.9375