In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset = pd.read_csv(r'C:\Users\LENOVO\Downloads\Datasets\diabetes - Classification.csv')
dataset.head()

Pregnancies  Glucose  Blood Pressure  SkinThickness  Insulin   BMI  \
0            0      148              72             35        0  33.6   
1            1       85              64             29        0  26.6   
2            8      183              64              0        0  26.6   
3            1       89              66             23       94  26.6   
4            0      137              40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df = dataset.copy()

In [6]:
X = dataset.drop(['Outcome'], axis = 1)
y = dataset.loc[:, 'Outcome']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train

array([[-0.52310111, -1.15139792, -3.75234879, ..., -4.13415791,
        -0.49073479, -1.03594038],
       [ 1.58995205, -0.27664283,  0.68049236, ..., -0.48876049,
         2.41502991,  1.48710085],
       [-0.82496585,  0.56687102, -1.26563302, ..., -0.42412578,
         0.54916055, -0.94893896],
       ...,
       [ 1.89181679, -0.62029661,  0.89672851, ...,  1.76052728,
         1.981245  ,  0.44308379],
       [-1.12683058,  0.62935353, -3.75234879, ...,  1.34686516,
        -0.78487662, -0.33992901],
       [-1.12683058,  0.12949347,  1.4373189 , ..., -1.22559614,
        -0.61552223, -1.03594038]])

In [11]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [12]:
y_pred = lr.predict(X_test)

In [13]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
      dtype=int64)

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [16]:
confusion_matrix(y_test, y_pred)

array([[79, 20],
       [18, 37]], dtype=int64)

In [17]:
accuracy_score(y_test, y_pred)

0.7532467532467533

In [18]:
(79+37)/(79+20+18+37)

0.7532467532467533