In [ ]:
import numpy
import numpy as np
from numpy import *

In [2]:
import numpy

In [3]:
arr = numpy.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
from numpy import *

In [8]:
arr2 = array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [9]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [10]:
arr1.dtype

dtype('int32')

In [11]:
arr1 = np.array([1,2,3,4,5.0])
arr1

array([1., 2., 3., 4., 5.])

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr1 = np.array([1,2,3,4,5.0], dtype = 'int')
arr1

array([1, 2, 3, 4, 5])

In [14]:
arr1 = np.array([1,2,3,4,5], dtype = float)
arr1

array([1., 2., 3., 4., 5.])

In [ ]:
# Linspace, Log Space

In [20]:
arr3 = np.linspace(0,15, 10)
arr3

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [21]:
3.33333333 - 1.66666667

1.66666666

In [22]:
11.66666667 - 10

1.6666666699999997

In [23]:
15 - 13.33333333

1.6666666699999997

In [25]:
arr4 = np.logspace(0,15, 100)
arr4

array([1.00000000e+00, 1.41747416e+00, 2.00923300e+00, 2.84803587e+00,
       4.03701726e+00, 5.72236766e+00, 8.11130831e+00, 1.14975700e+01,
       1.62975083e+01, 2.31012970e+01, 3.27454916e+01, 4.64158883e+01,
       6.57933225e+01, 9.32603347e+01, 1.32194115e+02, 1.87381742e+02,
       2.65608778e+02, 3.76493581e+02, 5.33669923e+02, 7.56463328e+02,
       1.07226722e+03, 1.51991108e+03, 2.15443469e+03, 3.05385551e+03,
       4.32876128e+03, 6.13590727e+03, 8.69749003e+03, 1.23284674e+04,
       1.74752840e+04, 2.47707636e+04, 3.51119173e+04, 4.97702356e+04,
       7.05480231e+04, 1.00000000e+05, 1.41747416e+05, 2.00923300e+05,
       2.84803587e+05, 4.03701726e+05, 5.72236766e+05, 8.11130831e+05,
       1.14975700e+06, 1.62975083e+06, 2.31012970e+06, 3.27454916e+06,
       4.64158883e+06, 6.57933225e+06, 9.32603347e+06, 1.32194115e+07,
       1.87381742e+07, 2.65608778e+07, 3.76493581e+07, 5.33669923e+07,
       7.56463328e+07, 1.07226722e+08, 1.51991108e+08, 2.15443469e+08,
      

In [26]:
# arange = a range
range_arr = np.arange(1,25)
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [29]:
range_arr = np.arange(1, 110)
range_arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109])

In [31]:
# Zeros
z_arr = np.zeros(50)
z_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
# ones
z_arr = np.ones(50, dtype = int)
z_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [37]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,10])
arr3 = arr1 + arr2
arr3

array([ 5,  7,  9, 11, 15])

In [39]:
np.concatenate([arr1, arr2])

array([ 1,  2,  3,  4,  5,  4,  5,  6,  7, 10])

In [ ]:
# Trignometry

In [40]:
arr1 = np.array([1,2,3,4,5])

In [41]:
print (np.sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [42]:
print (np.cos(arr1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [43]:
print (np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [45]:
np.sqrt(64)

8.0

In [46]:
print (max(arr1))

5


In [47]:
print (min(arr1))

1


In [48]:
print (sum(arr1))

15


## Copy

In [49]:
arr1 = np.array([1,2,3,4,5])

In [50]:
arr2 = arr1

In [51]:
arr2

array([1, 2, 3, 4, 5])

In [52]:
arr2[1] = 11

In [53]:
arr2

array([ 1, 11,  3,  4,  5])

In [54]:
arr1

array([ 1, 11,  3,  4,  5])

In [55]:
print (id(arr1))

2367496537072


In [56]:
print (id(arr2))

2367496537072


#### Shallow and Deep Copy

In [57]:
arr1 = np.array([1,2,3,4,5])

In [58]:
# Shallow
arr2 = arr1.view()

In [59]:
print (id(arr1))
print (id(arr2))

2367496536880
2367496608048


In [60]:
arr2[1] = 11

In [61]:
arr2

array([ 1, 11,  3,  4,  5])

In [62]:
arr1

array([ 1, 11,  3,  4,  5])

In [63]:
# Deep Copy
arr1 = np.array([1,2,3,4,5])

In [64]:
arr2 = arr1.copy()

In [65]:
arr2[1] = 11

In [66]:
arr2

array([ 1, 11,  3,  4,  5])

In [67]:
arr1

array([1, 2, 3, 4, 5])

In [68]:
print (id(arr1))
print (id(arr2))

2367496537168
2367496537264
