In [1]:
import numpy as np

In [22]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [23]:
arr.shape

(3,)

In [3]:
arr.ndim

1

In [24]:
arr = np.array([[1,2,3]])
arr.ndim

2

In [25]:
arr.shape

(1, 3)

In [14]:
arr = np.array([[[1,2,3]]])
arr.ndim
arr

array([[[1, 2, 3]]])

In [8]:
arr2d = np.array([[1,2,3], [4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2d = np.array([[1,2,3], [4,5,6], [5,6,7]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [33]:
arr3d = np.array([[[1,2,3], [4,5,6], [5,6,7], [11,2,1]], [[1,2,3], [4,5,6], [5,6,7], [11,2,1]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  7],
        [11,  2,  1]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  7],
        [11,  2,  1]]])

In [34]:
arr3d.shape

(2, 4, 3)

In [15]:
arr3d.dtype

dtype('int32')

In [17]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  7],
        [11,  2,  1]]])

In [20]:
arr3d[2,2]

7

In [ ]:
arr2d = np.array([[1,2,3], [4,5,6], [5,6,7], [11,2,1]])
arr2d

In [36]:
arr4d = np.array([[[[1,2,3], [4,5,6], [5,6,7], [11,2,1]], [[1,2,3], [4,5,6], [5,6,7], [11,2,1]], [[1,2,3], [4,5,6], [5,6,7], [11,2,1]]], [[[1,2,3], [4,5,6], [5,6,7], [11,2,1]], [[1,2,3], [4,5,6], [5,6,7], [11,2,1]], [[1,2,3], [4,5,6], [5,6,7], [11,2,1]]]])
arr4d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 5,  6,  7],
         [11,  2,  1]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 5,  6,  7],
         [11,  2,  1]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 5,  6,  7],
         [11,  2,  1]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 5,  6,  7],
         [11,  2,  1]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 5,  6,  7],
         [11,  2,  1]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 5,  6,  7],
         [11,  2,  1]]]])

In [37]:
arr4d.shape

(2, 3, 4, 3)

In [39]:
arr4d[1, 2,1,2 ]

6

In [40]:
list1 = [[1,2,3], [3,4,5]]
arr2d = np.array(list1)
arr2d

array([[1, 2, 3],
       [3, 4, 5]])

In [41]:
list1 = [[1,2,5], [3,1,5]]
arr2d1 = np.array(list1)
arr2d1

array([[1, 2, 5],
       [3, 1, 5]])

In [42]:
arr2d > arr2d1

array([[False, False, False],
       [False,  True, False]])

In [43]:
arr2d < arr2d1

array([[False, False,  True],
       [False, False, False]])

In [44]:
arr2d.std()

1.2909944487358056

In [45]:
arr2d.min()

1

In [46]:
arr2d.var()

1.6666666666666667

In [ ]:
#flatten and Ravel

In [47]:
arr2d.ndim

2

In [50]:
arr2d

array([[1, 2, 3],
       [3, 4, 5]])

In [49]:
aar_f = arr2d.flatten()
aar_f

array([1, 2, 3, 3, 4, 5])

In [51]:
aar_r = arr2d.ravel()
aar_r

array([1, 2, 3, 3, 4, 5])

In [52]:
aar_r[3] = 11

In [53]:
aar_r

array([ 1,  2,  3, 11,  4,  5])

In [54]:
arr2d

array([[ 1,  2,  3],
       [11,  4,  5]])

In [55]:
aar_f[0] = 20 

In [56]:
aar_f

array([20,  2,  3,  3,  4,  5])

In [57]:
arr2d

array([[ 1,  2,  3],
       [11,  4,  5]])

In [58]:
arr2d.shape

(2, 3)

In [59]:
arr2d.reshape(3,2)

array([[ 1,  2],
       [ 3, 11],
       [ 4,  5]])

In [60]:
arr2d = np.array([[1,2,3], [4,5,6], [5,6,7], [11,2,1]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [11,  2,  1]])

In [62]:
arr2d.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  5,  6],
       [ 7, 11,  2,  1]])

In [ ]:
12
4*3
3*4
6*2
2*6

In [63]:
arr2d.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 5,  6],
       [ 7, 11],
       [ 2,  1]])

In [64]:
arr2d.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6,  7, 11,  2,  1]])

In [65]:
arr2d1 = np.array([[1,2,3], [4,5,6], [5,6,7], [11,2,1]])
arr2d1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [11,  2,  1]])

In [66]:
np.concatenate([arr2d, arr2d1], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [11,  2,  1],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [11,  2,  1]])

In [69]:
np.concatenate([arr2d, arr2d1], axis = 1)

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 5,  6,  7,  5,  6,  7],
       [11,  2,  1, 11,  2,  1]])

In [70]:
np.vstack([arr2d, arr2d1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [11,  2,  1],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [11,  2,  1]])

In [71]:
np.hstack([arr2d, arr2d1])

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 5,  6,  7,  5,  6,  7],
       [11,  2,  1, 11,  2,  1]])