In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r'C:\Users\LENOVO\Downloads\Datasets\insurance - Regression.csv')

In [3]:
df = dataset.copy()

In [4]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df.shape

(1338, 7)

In [6]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [7]:
df1 = pd.get_dummies(df, columns = ['sex', 'smoker', 'region'], drop_first = True)
df1.head()

age     bmi  children      charges  sex_male  smoker_yes  region_northwest  \
0   19  27.900         0  16884.92400         0           1                 0   
1   18  33.770         1   1725.55230         1           0                 0   
2   28  33.000         3   4449.46200         1           0                 0   
3   33  22.705         0  21984.47061         1           0                 1   
4   32  28.880         0   3866.85520         1           0                 1   

   region_southeast  region_southwest  
0                 0                 1  
1                 1                 0  
2                 1                 0  
3                 0                 0  
4                 0                 0

In [8]:
df2 = pd.get_dummies(df, columns = ['sex', 'smoker', 'region'], drop_first = False)
df2.head()

age     bmi  children      charges  sex_female  sex_male  smoker_no  \
0   19  27.900         0  16884.92400           1         0          0   
1   18  33.770         1   1725.55230           0         1          1   
2   28  33.000         3   4449.46200           0         1          1   
3   33  22.705         0  21984.47061           0         1          1   
4   32  28.880         0   3866.85520           0         1          1   

   smoker_yes  region_northeast  region_northwest  region_southeast  \
0           1                 0                 0                 0   
1           0                 0                 0                 1   
2           0                 0                 0                 1   
3           0                 0                 1                 0   
4           0                 0                 1                 0   

   region_southwest  
0                 1  
1                 0  
2                 0  
3                 0  
4                 0

In [9]:
df2 = df2.drop(['sex_male', 'smoker_yes', 'region_southeast'], axis = 1)
df2

age     bmi  children      charges  sex_female  smoker_no  \
0      19  27.900         0  16884.92400           1          0   
1      18  33.770         1   1725.55230           0          1   
2      28  33.000         3   4449.46200           0          1   
3      33  22.705         0  21984.47061           0          1   
4      32  28.880         0   3866.85520           0          1   
...   ...     ...       ...          ...         ...        ...   
1333   50  30.970         3  10600.54830           0          1   
1334   18  31.920         0   2205.98080           1          1   
1335   18  36.850         0   1629.83350           1          1   
1336   21  25.800         0   2007.94500           1          1   
1337   61  29.070         0  29141.36030           1          0   

      region_northeast  region_northwest  region_southwest  
0                    0                 0                 1  
1                    0                 0                 0  
2                    0                 0                 0  
3                    0                 1                 0  
4                    0                 1                 0  
...                ...               ...               ...  
1333                 0                 1                 0  
1334                 1                 0                 0  
1335                 0                 0                 0  
1336                 0                 0                 1  
1337                 0                 1                 0  

[1338 rows x 9 columns]

In [14]:
df1.head()

age     bmi  children      charges  sex_male  smoker_yes  region_northwest  \
0   19  27.900         0  16884.92400         0           1                 0   
1   18  33.770         1   1725.55230         1           0                 0   
2   28  33.000         3   4449.46200         1           0                 0   
3   33  22.705         0  21984.47061         1           0                 1   
4   32  28.880         0   3866.85520         1           0                 1   

   region_southeast  region_southwest  
0                 0                 1  
1                 1                 0  
2                 1                 0  
3                 0                 0  
4                 0                 0

In [10]:
X = df1.drop('charges', axis = 1)
y = df1.drop(['age', 'bmi', 'children', 'sex_male', 'smoker_yes', 'region_northwest', 
              'region_southeast', 'region_southwest'], axis = 1)

In [12]:
y.head()

charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [13]:
X.children.value_counts()

0    574
1    324
2    240
3    157
4     25
5     18
Name: children, dtype: int64

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[['age', 'bmi']] = sc.fit_transform(X[['age', 'bmi']])

In [16]:
X

age       bmi  children  sex_male  smoker_yes  region_northwest  \
0    -1.438764 -0.453320         0         0           1                 0   
1    -1.509965  0.509621         1         1           0                 0   
2    -0.797954  0.383307         3         1           0                 0   
3    -0.441948 -1.305531         0         1           0                 1   
4    -0.513149 -0.292556         0         1           0                 1   
...        ...       ...       ...       ...         ...               ...   
1333  0.768473  0.050297         3         1           0                 1   
1334 -1.509965  0.206139         0         0           0                 0   
1335 -1.509965  1.014878         0         0           0                 0   
1336 -1.296362 -0.797813         0         0           0                 0   
1337  1.551686 -0.261388         0         0           1                 1   

      region_southeast  region_southwest  
0                    0                 1  
1                    1                 0  
2                    1                 0  
3                    0                 0  
4                    0                 0  
...                ...               ...  
1333                 0                 0  
1334                 0                 0  
1335                 1                 0  
1336                 0                 1  
1337                 0                 0  

[1338 rows x 8 columns]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .2, random_state = 42)

In [29]:
X_train.corr()

age       bmi  children  sex_male  smoker_yes  \
age               1.000000  0.118274  0.060999 -0.008459   -0.052035   
bmi               0.118274  1.000000 -0.005040  0.015293   -0.003450   
children          0.060999 -0.005040  1.000000  0.017080    0.013994   
sex_male         -0.008459  0.015293  0.017080  1.000000    0.070908   
smoker_yes       -0.052035 -0.003450  0.013994  0.070908    1.000000   
region_northwest  0.013019 -0.112666  0.033319  0.017047   -0.030547   
region_southeast -0.015068  0.247317 -0.025133 -0.008217    0.051450   
region_southwest  0.022307  0.010248 -0.002450 -0.013911   -0.033688   

                  region_northwest  region_southeast  region_southwest  
age                       0.013019         -0.015068          0.022307  
bmi                      -0.112666          0.247317          0.010248  
children                  0.033319         -0.025133         -0.002450  
sex_male                  0.017047         -0.008217         -0.013911  
smoker_yes               -0.030547          0.051450         -0.033688  
region_northwest          1.000000         -0.336290         -0.320954  
region_southeast         -0.336290          1.000000         -0.343194  
region_southwest         -0.320954         -0.343194          1.000000

In [18]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(random_state = 0)
rfr.fit(X_train, y_train)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4496\2732545983.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfr.fit(X_train, y_train)


RandomForestRegressor(random_state=0)

In [19]:
y_pred = rfr.predict(X_test)

In [20]:
from sklearn.metrics import r2_score, mean_squared_error

In [21]:
r2_score(y_test, y_pred)

0.8640099135651829

In [25]:
importance = rfr.feature_importances_
importance

array([0.13396469, 0.21178401, 0.02073361, 0.00678334, 0.61074257,
       0.00584718, 0.00569266, 0.00445194])

In [24]:
feat_name = X.columns
feat_name

Index(['age', 'bmi', 'children', 'sex_male', 'smoker_yes', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')

In [27]:
tree_result = pd.DataFrame({'Feature':feat_name, 'importance':importance})
tree_result

Feature  importance
0               age    0.133965
1               bmi    0.211784
2          children    0.020734
3          sex_male    0.006783
4        smoker_yes    0.610743
5  region_northwest    0.005847
6  region_southeast    0.005693
7  region_southwest    0.004452

In [28]:
tree_result_sort = tree_result.sort_values(by = 'importance', ascending = False)
tree_result_sort

Feature  importance
4        smoker_yes    0.610743
1               bmi    0.211784
0               age    0.133965
2          children    0.020734
3          sex_male    0.006783
5  region_northwest    0.005847
6  region_southeast    0.005693
7  region_southwest    0.004452

### Random Forest Classifier

In [30]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree

In [31]:
df = pd.read_csv(r'C:\Users\LENOVO\Downloads\Datasets\Social_Network_Ads - Classification.csv')
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [32]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [34]:
X1 = sc.fit_transform(X)
X1

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.2, random_state=42)

In [36]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [37]:
y_pred = rfc.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [39]:
confusion_matrix(y_test, y_pred)

array([[46,  6],
       [ 3, 25]], dtype=int64)

In [40]:
accuracy_score(y_test, y_pred)

0.8875