In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv(r'C:\Users\LENOVO\Downloads\Datasets\Fit Bit Easy - Regression.csv')
dataset.head()

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366    3/25/2016       11004           7.11             7.11   
1  1503960366    3/26/2016       17609          11.55            11.55   
2  1503960366    3/27/2016       12736           8.53             8.53   
3  1503960366    3/28/2016       13231           8.93             8.93   
4  1503960366    3/29/2016       12041           7.85             7.85   

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                2.57                      0.46   
1                       0.0                6.92                      0.73   
2                       0.0                4.66                      0.16   
3                       0.0                3.19                      0.79   
4                       0.0                2.16                      1.09   

   LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                 4.07                      0.0                 33   
1                 3.91                      0.0                 89   
2                 3.71                      0.0                 56   
3                 4.95                      0.0                 39   
4                 4.61                      0.0                 28   

   FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  \
0                   12                   205               804   
1                   17                   274               588   
2                    5                   268               605   
3                   20                   224              1080   
4                   28                   243               763   

   Calories - Target  
0               1819  
1               2154  
2               1944  
3               1932  
4               1886

In [3]:
X = dataset.loc[:, 'TotalSteps']
y = dataset.loc[:, 'Calories - Target']

In [5]:
X = pd.DataFrame(X)
y = pd.DataFrame(y)

In [7]:
y

Calories - Target
0                 1819
1                 2154
2                 1944
3                 1932
4                 1886
..                 ...
452               4196
453               3841
454               4526
455               2820
456                938

[457 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
y_train

Calories - Target
17                1811
66                2130
410               1657
320               1903
31                1276
..                 ...
106               2206
270               2235
348               3920
435               2667
102               1508

[365 rows x 1 columns]

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lin_reg = LinearRegression()

In [17]:
lin_reg.fit(X_train, y_train)

LinearRegression()

In [18]:
pred = lin_reg.predict(X_test)

In [19]:
pred

array([[2890.77953496],
       [3345.78467033],
       [1629.16667546],
       [1629.16667546],
       [2605.34100392],
       [2344.50193023],
       [2112.84290251],
       [2222.86185489],
       [1629.16667546],
       [1742.40900502],
       [2783.05087689],
       [2130.14734837],
       [1629.16667546],
       [2684.14409317],
       [2146.6883628 ],
       [2080.10017651],
       [2924.11604097],
       [2816.89633718],
       [2018.68635884],
       [2486.41535146],
       [2934.80408106],
       [2077.89470792],
       [2206.06636332],
       [2504.56805447],
       [1629.16667546],
       [2263.49337239],
       [2733.85196217],
       [2923.60708668],
       [2478.78103711],
       [1736.04707639],
       [2867.96141762],
       [1629.16667546],
       [1852.34313168],
       [2264.08715239],
       [2554.61522634],
       [2545.70852626],
       [2656.91503865],
       [2544.35131482],
       [1816.97080852],
       [3176.98149744],
       [2180.44899738],
       [1863.879

In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, pred)

0.46687053878486495

In [22]:
lin_reg.predict([[2200]])

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[1815.78324851]])

In [23]:
list1 = [1000, 1200, 1300, 1800, 900, 2900, 2100]

In [24]:
for i in list1:
    print(lin_reg.predict([[i]]))

[[1713.99239048]]
[[1730.95753349]]
[[1739.44010499]]
[[1781.8529625]]
[[1705.50981898]]
[[1875.16124902]]
[[1807.30067701]]


C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does 

In [25]:
lin_reg.coef_

array([[0.08482572]])

In [26]:
lin_reg.intercept_

array([1629.16667546])

In [28]:
X_test

TotalSteps
304       14873
39        20237
341           0
218           0
155       11508
..          ...
137           0
93         5142
57         6556
154        7618
24         1675

[92 rows x 1 columns]

In [32]:
1629.16667546 + (0.08482572*20237)

3345.7847711

In [30]:
pred

array([[2890.77953496],
       [3345.78467033],
       [1629.16667546],
       [1629.16667546],
       [2605.34100392],
       [2344.50193023],
       [2112.84290251],
       [2222.86185489],
       [1629.16667546],
       [1742.40900502],
       [2783.05087689],
       [2130.14734837],
       [1629.16667546],
       [2684.14409317],
       [2146.6883628 ],
       [2080.10017651],
       [2924.11604097],
       [2816.89633718],
       [2018.68635884],
       [2486.41535146],
       [2934.80408106],
       [2077.89470792],
       [2206.06636332],
       [2504.56805447],
       [1629.16667546],
       [2263.49337239],
       [2733.85196217],
       [2923.60708668],
       [2478.78103711],
       [1736.04707639],
       [2867.96141762],
       [1629.16667546],
       [1852.34313168],
       [2264.08715239],
       [2554.61522634],
       [2545.70852626],
       [2656.91503865],
       [2544.35131482],
       [1816.97080852],
       [3176.98149744],
       [2180.44899738],
       [1863.879