In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r'C:\Users\LENOVO\Downloads\Datasets\creditcard.csv')

In [3]:
df = dataset.copy()

In [4]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [5]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [6]:
df.Class.value_counts(normalize = True)

0    0.998273
1    0.001727
Name: Class, dtype: float64

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc = StandardScaler()
df['Amount'] = sc.fit_transform(np.array(df['Amount']).reshape(-1,1))
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28    Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  0.244964   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724 -0.342475   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  1.160686   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  0.140534   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153 -0.073403   
...          ...       ...       ...       ...       ...       ...       ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731 -0.350151   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527 -0.254117   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561 -0.081839   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533 -0.313249   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  0.514355   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [9]:
df.drop(['Time','Amount'], inplace = True, axis = 1)

In [10]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Class  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053      0  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724      0  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752      0  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458      0  
4  0.141267 -0.206010  0.502292  0.219422  0.215153      0  

[5 rows x 29 columns]

In [11]:
X = df.iloc[:, :-1]
y = df.iloc[:,-1]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .2, random_state = 42)

In [13]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [14]:
y_pred_normal = lr.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_pred_normal)

0.9991046662687406

In [16]:
confusion_matrix(y_test, y_pred_normal)

array([[56855,     9],
       [   42,    56]], dtype=int64)

# SMOTE

In [17]:
# !pip install imblearn

In [18]:
from imblearn.over_sampling import SMOTE

In [19]:
sm = SMOTE(random_state = 11)
X_train_new, y_train_new = sm.fit_resample(X_train, y_train)

In [20]:
from sklearn.linear_model import LogisticRegression
lr_sm = LogisticRegression()
lr_sm.fit(X_train_new, y_train_new)

LogisticRegression()

In [21]:
pred_sm = lr_sm.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, pred_sm)

0.9747375443277975

In [23]:
# Old Confusion matrix
confusion_matrix(y_test, y_pred_normal)

array([[56855,     9],
       [   42,    56]], dtype=int64)

In [24]:
TP = 56855
TN = 56
Fp = 9
FN = 42

In [25]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred_normal)

0.5714285714285714

In [26]:
# SMOTE Confusion matrix
confusion_matrix(y_test, pred_sm)

array([[55433,  1431],
       [    8,    90]], dtype=int64)

In [27]:
# TP = 55433
# TN = 90
# FP = 1431
# FN = 8

In [28]:
from sklearn.metrics import recall_score
recall_score(y_test, pred_sm)

0.9183673469387755

# Down sampling / Undersampling

In [29]:
from imblearn.under_sampling import NearMiss
nr = NearMiss()

In [30]:
X_train_nr, y_train_nr = sm.fit_resample(X_train, y_train)

In [31]:
from sklearn.linear_model import LogisticRegression
lr_nr = LogisticRegression()
lr_nr.fit(X_train_nr, y_train_nr)

LogisticRegression()

In [32]:
pred_nr = lr_nr.predict(X_test)

In [33]:
accuracy_score(y_test, pred_nr)

0.9747375443277975

In [34]:
confusion_matrix(y_test, pred_nr)

array([[55433,  1431],
       [    8,    90]], dtype=int64)

In [35]:
# SMOTE Confusion matrix
confusion_matrix(y_test, pred_sm)

array([[55433,  1431],
       [    8,    90]], dtype=int64)